version: '3.7'

services:
  next:
    build: .
    image: finkrer.wtf:latest
    container_name: next
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external:
      name: reverse_proxy
